services :
- type : web
  name: fastapi
  runtime: docker
  plan: free
  repo: https://github.com/itterate/2023-backend-firstLecture.git
  region: frankfurt
  branch: main
  - envVars:
    - key: MONGO_URL
    sync: false
  buildFilter:
    paths:
    - app/**
